### ISSUE TITLE
disnake doesnt install properly (?)

### ISSUE THREAD

**Issue by modpotato** [ShyAssassin/Stable-Defusion-Bot#1]
Traceback (most recent call last):
  File "/content/Stable-Diffusion-Bot/sdb/main.py", line 8, in <module>
    from Core.bot import SDB
  File "/content/Stable-Diffusion-Bot/sdb/Core/__init__.py", line 1, in <module>
    from .bot import SDB
  File "/content/Stable-Diffusion-Bot/sdb/Core/bot.py", line 2, in <module>
    import disnake
ModuleNotFoundError: No module named 'disnake'

**Comment by ShyAssassin** [comment]
did you install poetry and python 3.10.* then install all dependencies using `poetry install`?
also how are you starting the bot, are you using `poetry run python sdb/main.py`?

**Comment by ShyAssassin** [comment]
Closing due to lack of activity
